---
name: starling
description: A medium-sized passerine.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
      - source: usr/lib/firmware
        destination: /usr/lib/firmware
      - source: etc/greetd
        destination: /etc/greetd

  - type: bling
    install:
        - rpmfusion

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      keys:
        - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      copr:
        - lizardbyte/beta
    install:
      packages:
        - brave-origin
        - brightnessctl
        - btop
        - cargo
        - cava
        - chezmoi
        - cliphist
        - ddcutil
        - dialog
        - eog
        - fastfetch
        - fira-code-fonts
        - freerdp
        - fuse-libs
        - gamescope
        - gamescope-session-steam
        - gnome-calculator
        - gnome-clocks
        - gnome-disk-image-mounter
        - gnome-disks
        - gnome-keyring-pam
        - gparted
        - greetd
        - gstreamer1-plugins-ugly
        - ImageMagick
        - intel-media-driver
        - jetbrainsmono-nerd-fonts
        - kitty
        - libvirt
        - mangohud
        - mediawriter
        - mesa-va-drivers-freeworld
        - mesa-vulkan-drivers-freeworld
        - mpv
        - mpv-devel
        - nautilus
        - NetworkManager-openconnect
        - niri
        - nmap-ncat
        - noctalia
        - noctalia-greeter
        - noctalia-shell
        - openconnect
        - papers
        - python3-pip
        - qemu
        - qt6ct
        - screen
        - steam
        - sunshine
        - system-config-printer
        - tailscale
        - telnet
        - tuned-ppd
        - virt-manager
        - wayvnc
        - wlsunset
        - xdotool
        - xwininfo
        - yad
        - yazi
        - zed

    remove:
      packages:
        - htop

  - type: akmods
    install:
      - xone

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - com.ranfdev.DistroShelf
          - io.github.flattool.Ignition
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark
          - org.remmina.Remmina
          - page.codeberg.libre_menu_editor.LibreMenuEditor
          - io.github.kolunmi.Bazaar
          - io.missioncenter.MissionCenter
          - com.github.tchx84.Flatseal
          - org.atheme.audacious
          - page.tesk.Refine

  - type: signing

  - type: systemd
    system:
      enabled:
        - greetd
        - libvirtd
        - sshd
        - tailscaled

  - type: kargs
    kargs:
      - split_lock_detect=off
